-- Migration: add_fit_slots
-- Description: Add slot columns to Fit table

-- Add new columns to Fit table
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "highSlots" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "medSlots" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "lowSlots" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "rigSlots" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "subsystemSlots" JSONB;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "droneBay" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "cargo" JSONB DEFAULT '[]';
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "volley" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "ehp" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "capStable" BOOLEAN;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "capUse" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "capRecharge" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "cpuUsed" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "cpuTotal" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "pgUsed" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "pgTotal" REAL;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "highSlotCount" INTEGER;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "medSlotCount" INTEGER;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "lowSlotCount" INTEGER;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "rigSlotCount" INTEGER;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "Fit" ADD COLUMN IF NOT EXISTS "fitId" TEXT;

-- Add index on shipTypeId
CREATE INDEX IF NOT EXISTS "Fit_shipTypeId_idx" ON "Fit" ("shipTypeId");